[project]
name = "fakesnow"
description = "Mock SnowflakeDB locally"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "duckdb~=0.7.0",
    # include the pandas extra to get compatible version of pyarrow
    "snowflake-connector-python[pandas]",
    "sqlglot @ git+https://github.com/tobymao/sqlglot.git@7ee8a3c",
]

[project.optional-dependencies]
dev = [
    "black~=22.12",
    "build~=0.10",
    "docformatter~=1.5",
    "pandas",
    "pre-commit~=3.0",
    "pytest~=7.2",
    "ruff~=0.0.235",
]
# for debugging, see https://duckdb.org/docs/guides/python/jupyter.html
notebook = [
    "duckdb-engine",
    "ipykernel",
    "jupysql",
    "snowflake-sqlalchemy",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

# use PyCharm default line length of 120

[build-system]
requires = ["setuptools~=66.1", "wheel~=0.37"]

[tool.black]
line-length = 120

[tool.docformatter]
pre-summary-newline = true
recursive = true
wrap-descriptions = 120
wrap-summaries = 120

[tool.ruff]
line-length = 120

# rules to enable/ignore
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # type annotations
    "ANN",
    # pep8-naming
    "N",
    # bugbear
    "B",
    # isort
    "I",
]
ignore = [
    # allow untyped self and cls args, and no return type from dunder methods
    "ANN101",
    "ANN102",
    "ANN204",
    # allow == True because pandas dataframes overload equality
    "E712",
    # only relevant for python >= 3.10
    "B905"
]
# first-party imports for sorting
src = ["."]

fix = true

[tool.ruff.per-file-ignores]
# imports in __init__.py don't need to be used in __init__.py
"__init__.py" = ["F401"]
# test functions don't need return types
"tests/*" = ["ANN201", "ANN202"]

[tool.ruff.flake8-annotations]
# allow *args: Any, **kwargs: Any
allow-star-arg-any = true
